version: '3'
services:
  es:
    image: elasticsearch:7.7.0
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es-learning-cluster
      - script.painless.regex.enabled=true
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    ports:
      - 9300:9200
    networks:
      - elastic
  kib:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kib
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
    networks:
      - elastic
volumes:
  es:
networks:
  elastic:
    driver: bridge